# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.4
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_objreader', [dirname(__file__)])
        except ImportError:
            import _objreader
            return _objreader
        if fp is not None:
            try:
                _mod = imp.load_module('_objreader', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _objreader = swig_import_helper()
    del swig_import_helper
else:
    import _objreader
del version_info
try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.


def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        object.__setattr__(self, name, value)
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr_nondynamic(self, class_type, name, static=1):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    if (not static):
        return object.__getattr__(self, name)
    else:
        raise AttributeError(name)

def _swig_getattr(self, class_type, name):
    return _swig_getattr_nondynamic(self, class_type, name, 0)


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object:
        pass
    _newclass = 0


class SwigPyIterator(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SwigPyIterator, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SwigPyIterator, name)

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _objreader.delete_SwigPyIterator
    __del__ = lambda self: None

    def value(self):
        return _objreader.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _objreader.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _objreader.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _objreader.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _objreader.SwigPyIterator_equal(self, x)

    def copy(self):
        return _objreader.SwigPyIterator_copy(self)

    def next(self):
        return _objreader.SwigPyIterator_next(self)

    def __next__(self):
        return _objreader.SwigPyIterator___next__(self)

    def previous(self):
        return _objreader.SwigPyIterator_previous(self)

    def advance(self, n):
        return _objreader.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _objreader.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _objreader.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _objreader.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _objreader.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _objreader.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _objreader.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self
SwigPyIterator_swigregister = _objreader.SwigPyIterator_swigregister
SwigPyIterator_swigregister(SwigPyIterator)

class Engine(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Engine, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Engine, name)
    __repr__ = _swig_repr

    def __init__(self):
        this = _objreader.new_Engine()
        try:
            self.this.append(this)
        except:
            self.this = this
    __swig_destroy__ = _objreader.delete_Engine
    __del__ = lambda self: None

    def is_league_running(self):
        return _objreader.Engine_is_league_running(self)

    def start(self):
        return _objreader.Engine_start(self)

    def read_string(self, *args):
        return _objreader.Engine_read_string(self, *args)

    def dump_memory(self, offset):
        return _objreader.Engine_dump_memory(self, offset)

    def object_addr(self, index):
        return _objreader.Engine_object_addr(self, index)

    def object_exist(self, index):
        return _objreader.Engine_object_exist(self, index)

    def print_debug_info(self):
        return _objreader.Engine_print_debug_info(self)

    def get_module_addr(self):
        return _objreader.Engine_get_module_addr(self)

    def read_byte(self, offset):
        return _objreader.Engine_read_byte(self, offset)

    def read_short(self, offset):
        return _objreader.Engine_read_short(self, offset)

    def read_int(self, offset):
        return _objreader.Engine_read_int(self, offset)

    def read_float(self, offset):
        return _objreader.Engine_read_float(self, offset)
Engine_swigregister = _objreader.Engine_swigregister
Engine_swigregister(Engine)

# This file is compatible with both classic and new-style classes.


